### ISSUE TITLE
Can't figure out how to run multiple instances pointing at multiple graphics cards

### ISSUE THREAD

**Issue by LyfeOnEdge** [rbbrdckybk/ai-art-generator#11]

**Comment by LyfeOnEdge** [comment]
For example I have a GTX 1080 Ti and a GTX 1070 and wish to run two instances, one using each card. Is this possible?

**Comment by LyfeOnEdge** [comment]
After over a week of near constant use with multiple graphics cards I have had no issues. Stability running two instances of the script pointed at two different graphics devices is great.

**Comment by rbbrdckybk** [comment]
Merged! Only have 1 GPU myself so can't test thoroughly but your changes look pretty straightforward - thanks!
