### ISSUE TITLE
Up-Scaling and Diffusion Not Working?

### ISSUE THREAD

**Issue by Error404-RedRose** [rbbrdckybk/ai-art-generator#13]
Is there any way to upscale a generated image? Would that be done by diffusion? but if so the problem then is my Diffusion is missing cv2 Module. Everything was installed correctly also. But just a general question of how Upscaling is done

**Comment by RyanNeumann** [comment]
Upscaling was mentioned in the Requirements -

Generating small images and then upscaling via [ESRGAN](https://github.com/xinntao/Real-ESRGAN) or some other package provides very good results as well.

I have been using Real-ESRGAN for upscaling and has been pretty straight forward thus far.

**Comment by Error404-RedRose** [comment]
thanks so much ^~^ I appreciate the straightfoward help because I couldn't find that part. thanks for linking that also

**Comment by rbbrdckybk** [comment]
Just cleaning up open issues, ESRGAN/GFPGAN upscaling is now optionally integrated for stable diffusion.
