### ISSUE TITLE
Training the AI?

### ISSUE THREAD

**Issue by Error404-RedRose** [rbbrdckybk/ai-art-generator#14]
how does training work? I know it uses checkpoints as trained data but is there a way I can train it manually for my art and specific images?

**Comment by ZeroCool940711** [comment]
Hi there, you can check the `Training` section on the [`Taming Transformers`](https://github.com/CompVis/taming-transformers#training) repository for more information on how to train the model with technically any kind of images you want, be it art or anything else, it depends on what kind of model you want to train but for example custom data section on the repository I mentioned before describes how to train the VQGAN model and these are the steps to do so:

### Training on custom data.
1- Clone the Taming Transformers repository.
2- Create a conda environment with `conda env create -f environment.yaml`
3- Activate the environment with `conda activate taming` and then install the repo with `pip install -e .`
4- Put your .jpg files in a folder for example `data/your_folder`
5- Create 2 text files with the path to the files, one named `train.txt` and the other `test.txt` that point to the files in your training and test set respectively, you can create a single txt file with all the path to the images and then split it in two to get the test ant train.txt files with these two commands, `find data/your_folder -name "*.jpg" > images.txt`, this will create a singel file called `images.txt` with the paths to the images on  `data/your_folder`, then you can open that file and go to the end to see how many lines it has, divide it by 2 to find the half of it and then use `split -l half_of_number_of_lines` to split that file in half and you will get two files on the same folder without any extension containing half of the paths on each of them, rename them to `train.txt` and `test.txt` and you're ready to go to the next step.
6- Modify the configs/custom_vqgan.yaml to point to these 2 files (line 36 for the `train.txt` file path and line 41 for the `test.txt` file path)
7- Start training, to do this open a command line and run `python main.py --base configs/custom_vqgan.yaml -t True --gpus xx, xx2` where xx and xx2 are the numbers of the GPUs you want to use for training. Use `--gpus 0,` (with a trailing comma) to train on a single GPU.
`
I added some extra information that is not mentioned on taming transformers repository to make things a bit easier. Hope it helps you.
