### ISSUE TITLE
Error when running + Where do I get the images?

### ISSUE THREAD

**Issue by vrotmelk** [rbbrdckybk/ai-art-generator#16]
RuntimeError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Also the images arent in the output folder.

**Comment by rbbrdckybk** [comment]
Looks like you have 4GB of VRAM - you'll need more than that. 8GB is a realistic minimum to create small images.

**Comment by vrotmelk** [comment]
So I wont be able to do it?

**Comment by rbbrdckybk** [comment]
I've added support for Stable Diffusion in the last few days, if you use that and set **!SD_LOW_MEMORY = yes** in your prompt file it should work at lower resolutions. (the VQGAN and CLIP-guided diffusion processes will definitely not work with 4GB VRAM).

You'll need to update your installation using the [latest instructions](https://github.com/rbbrdckybk/ai-art-generator#setup) starting at step 13.
