### ISSUE TITLE
RuntimeError: CUDA out of memory. diffusion

### ISSUE THREAD

**Issue by OussamaToumirt** [rbbrdckybk/ai-art-generator#19]
RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 3.45 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by rbbrdckybk** [comment]
Requirements state 8GB VRAM is the minimum; it looks like you have 4GB.
