### ISSUE TITLE
Style is a required field, not optional

### ISSUE THREAD

**Issue by xcorvis** [rbbrdckybk/ai-art-generator#20]
First, thanks for the work on this project, it's exactly what I was looking for, and the instructions are really good.

I found an issue where if you don't have a style listed, make_art.sh queues up 0 items and ends. The examples file notes that styles are optional, but since you must iterate on them to generate a prompt, it's actually not. 

https://github.com/rbbrdckybk/ai-art-generator/blob/03d71319f21675a32921f15e194231de5051ad22/make_art.py#L433

I think it was your intention but I'd like to be able to just list several complete prompts under "subject" and not require other fields.

Thanks!

**Comment by rbbrdckybk** [comment]
Thanks, noticed the issue yesterday myself - will get a fix in as soon as I have a minute. In the meantime, just throw a comma in the style section; it'll get appended to all of your subjects but won't affect the output images.

**Comment by xcorvis** [comment]
Excellent, thank you!

**Comment by rbbrdckybk** [comment]
Fixed - just a note that if you update, you'll also need to pull the latest from /rbbrdckybk/stable-diffusion
