### ISSUE TITLE
reproducing the art style based on people's picture

### ISSUE THREAD

**Issue by MinSong2** [rbbrdckybk/ai-art-generator#6]
Thank you for sharing your great work!  
I wonder what settings you used to generate the second rows of your example (two people's art style picture: sample03.jpg and sample04.jpg). Would you share the exact settings for that please? I tried the ffhq transformer but the results are quite different from yours and somewhat disappointing..!

**Comment by rbbrdckybk** [comment]
The example images were created before I embedded the settings used into the output file metadata, so I don't know exactly what I did. However, I'm pretty sure I used VQGAN for both of those, with RN50x4 as the CLIP model and FFHQ as the transformer.  I typically go for about 500 iterations and set cuts to 24 (you may need to lower this a bit if your GPU VRAM is limited).

An input image isn't strictly necessary, but I find that my keeper rate is much higher when I use a very basic line-art/vector face as my input. Something like this is a good choice:

![example face vector](https://i.pinimg.com/474x/bb/aa/0b/bbaa0bfab5e0f4fc8ae13a821ae87720.jpg)

With an input image, keep the learning rate a bit lower (maybe 0.08 - 0.09) for best results. Then just experiment with style prompts (e.g.: "in the style of a pencil sketch", etc) until you find something you like. You'll probably need to generate a few hundred images before you find some really good ones. Enjoy!

**Comment by MinSong2** [comment]
Thank you for your answer! It helps understand the process!!!
