### ISSUE TITLE
no module named clip

### ISSUE THREAD

**Issue by prais14** [rbbrdckybk/ai-art-generator#7]
i followed all the steps up to the test, and when i try 'python vqgan.py -s 128 128 -i 200 -p "a red apple" -o output/output.png' it says that there is no module named clip.

**Comment by rbbrdckybk** [comment]
Did you get any errors in step 5 of the instructions? Try re-running the command to clone the CLIP repo (make sure you're in your **ai-art-generator** directory first):

```
git clone https://github.com/openai/CLIP
```
