### ISSUE TITLE
Output image corners/borders getting deformed.

### ISSUE THREAD

**Issue by ZeroCool940711** [rbbrdckybk/ai-art-generator#9]
Hi there, after messing around with the code on this repo I noticed that some of my images were getting deformed corners/borders, mostly the top-right and bottom-left corners but in general all the corners seem to have this issue. This happened a few times on multiple images but there were other images were this didnt happen, maybe it's some of the settings Im using that are messing things up. I would appreciate any help as I havent been able to figure out the issue by myself and I definetely want to keep using this tool to see what I can generate with it. Here are some of the images I generated that have this issue, not sure if github will preserve the metadata on the images but if it doesnt let me know and I can just share the parameters I used when running the code to get those images so other people can easy reproduce the same or similar result.
![horror-village-with-dead-trees-a-snowy-tall-mountain-in-th-unreal-engine-high-detailk-ultra-hd-ray-tracing-realistic-photorealistic](https://user-images.githubusercontent.com/5977640/182548105-91ad5a62-dc0b-4727-a46c-8dc85c6b4cf8.png)
![painting-of-small-cabin-in-the-middle-of-snowy-mountains-in-the-winter-at-night-in-the-style-of-disney-trending-on-artstation-unreal-engine](https://user-images.githubusercontent.com/5977640/182548113-f59753d7-e7a6-4d0e-92d6-55f4860d3597.jpg)

Here are some images that do not have this issue:
![landscape-wallpaper-wallpaper-5](https://user-images.githubusercontent.com/5977640/182548400-88786e40-a34e-4982-aa53-137c5d988086.jpg)
![landscape-wallpaper-wallpaper-4](https://user-images.githubusercontent.com/5977640/182548402-ea97648a-c151-4653-9170-6d63f551fe59.jpg)
![landscape-wallpaper-wallpaper-3](https://user-images.githubusercontent.com/5977640/182548403-5a200d09-665c-4ea2-93e0-afa21d1099f4.jpg)
![landscape-wallpaper-wallpaper-2](https://user-images.githubusercontent.com/5977640/182548405-dc36a7c3-4fab-42ea-881a-2585c4173f6e.jpg)
![landscape-wallpaper-wallpaper](https://user-images.githubusercontent.com/5977640/182548406-19cc3c35-f420-4483-9d05-6ca278fc7bcf.jpg)

**Comment by rbbrdckybk** [comment]
That's normal behavior, and seems to happen with most AI Art generation techniques. I usually just crop a few pixels off the sides on images that I want to keep.
